### ISSUE TITLE
Nested Tabs

### ISSUE THREAD

**Issue by custa1200** [alexchizhovcom/pwstabs#10]
Lack of nested tabs is a show stopper for me :(

**Comment by varunsridharan** [comment]
+1

@custa1200 can you please tell me have you found any other plugin like this ?

**Comment by custa1200** [comment]
Not as of yet, I'm still hopeful this pwstabs gains the feature.

**Comment by varunsridharan** [comment]
@custa1200 

Ho ok

But i was able to create nested tabs using PWS Tabs
The below image has 2 tabs 1 nested

http://prntscr.com/abqtwv

**Comment by custa1200** [comment]
Don't think they will function correctly, even theproject ower says that they are not supported and are slated to be in version 2 in issue #4

**Comment by varunsridharan** [comment]
@custa1200 i know but for a simple nested tabs. its prefect. i can really see its working with just few small bugs.. for me its ok i think. but sure i am waiting for a new update on this

**Comment by varunsridharan** [comment]
@custa1200 and also i cant see any new commits. i dont think they are working on 2.0 ? :(

**Comment by varunsridharan** [comment]
@custa1200 
I have just found a paid script which is about 90% prefect or equal to this..

http://codecanyon.net/item/zozo-tabs/3327836

i just dont want to degrade this script but PWS Tabs is really good and nice.. 

I just wanted to share with you guys

**Comment by alexchizhovcom** [comment]
@custa1200  @technofreaky I can see that you guys really need this feature, I'll try to think on how to implement it. If you have any links or examples that could help to better understand what exactly you need, it would help.

**Comment by varunsridharan** [comment]
@alexchizhovcom  
Hi,
Thanks :) 
Kindly check this link http://codecanyon.net/item/zozo-tabs/3327836 that has a nested feature..
i also able to created nested feature in your current Version but it has some bugs..

if you are ok. i can also contribute for it

**Comment by alexchizhovcom** [comment]
@technofreaky @custa1200 its not updating the height yet, but see if its what you need:

https://jsfiddle.net/alexchizhov/h5a3coob/

**Comment by custa1200** [comment]
From memory it was the height that stopped me persuing using them.

**Comment by varunsridharan** [comment]
@alexchizhovcom i can see that you are setting the height via js
its good if you set it via css. make height : auto not fixed height.

and also when you have given position absolute for the below.. it makes me a big issue when using it in my site / software

``` css
.pws_tab_single {
    padding-right: 1.25em;
    position: absolute;
    top: 20px;
}
```

**Comment by varunsridharan** [comment]
@alexchizhovcom @custa1200

As you set to update the height only when the tab nav is clicked.. 

but you can set it as min-height via js and make height:auto via css
if you need i can code for it

**Comment by alexchizhovcom** [comment]
@custa1200  @technofreaky ok, give me an hour, just woke up, ill post a link when im done :)

**Comment by varunsridharan** [comment]
@alexchizhovcom sure and thanks .. you are really awesome.. :)

**Comment by custa1200** [comment]
No rush for me atm mate, I've parked what I was working on for the time being. But definitiely keen to see what the results are.

**Comment by varunsridharan** [comment]
@alexchizhovcom 
I am waiting for your update because i am using your script in one of my WordPress Plugin.. i need to release it  in next few days

**Comment by alexchizhovcom** [comment]
@technofreaky Height and nesting works already, but position:absolute was used to work with effects, trying to come up with something to make animation work now :)

**Comment by varunsridharan** [comment]
@alexchizhovcom 
Yes but nesting works only 50% and also some bugs

for eg

``` html
<div class="tab_set_1">

   <div data-pws-tab="anynameyouwant1" data-pws-tab-name="Tab Title 1">
<div class="tab_set_2">

<div data-pws-tab="anynameyouwant10" data-pws-tab-name="Tab Title 11">Our first tab</div>
   <div data-pws-tab="anynameyouwant20" data-pws-tab-name="Tab Title 12">Our second tab</div>
   <div data-pws-tab="anynameyouwant30" data-pws-tab-name="Tab Title 13">Our third tab</div>
</div>


</div>
   <div data-pws-tab="anynameyouwant2" data-pws-tab-name="Tab Title 2">Our second tab</div>
   <div data-pws-tab="anynameyouwant3" data-pws-tab-name="Tab Title 3">Our third tab</div>

</div>
```

When i trigger tab_set_1 via js tab_set_2 also get trigger and also it adds the tab_set_2 's nav to tab_set_1 

Please refer this image

Tab Output : http://prntscr.com/abt4bp
Tab HTML Code : http://prntscr.com/abt4j1
Tab JS Code : http://prntscr.com/abt4l9

If possible please try to remove position : absolute

**Comment by alexchizhovcom** [comment]
Nesting works here, I didn't push anything on git yet: https://jsfiddle.net/alexchizhov/h5a3coob/

**Comment by alexchizhovcom** [comment]
@custa1200 @technofreaky Ok, I removed position absolute, and as seems effects work now, and nested tabs work too. If you can help test all the effects and options, to make sure everything works ok, it'd be great. Ill push it on github after its tested.

**Comment by varunsridharan** [comment]
@alexchizhovcom sure i can help you in testing

**Comment by varunsridharan** [comment]
Vertical Position is not working 
http://prntscr.com/abt8cj

**Comment by alexchizhovcom** [comment]
@technofreaky Ok, so fixed effects finally. Vertical positioning is fixed, and now you can set positioning for every nested tabs separetaly. So you can have Vertical, vertical, horizontal, etc.. Check it out, tell me, if some doesn't work right.

https://jsfiddle.net/alexchizhov/h5a3coob/

**Comment by custa1200** [comment]
Looked at it on an iPhone and the horizontal inner tabs "throb" constantly with the tabs growing and shrinking in size.

**Comment by alexchizhovcom** [comment]
@custa1200 Can you please post a screenshot?

**Comment by custa1200** [comment]
Not sure where I can post them, can't seem to post in here.

**Comment by alexchizhovcom** [comment]
Can you send a screenshot to my email? ac@alexchizhov.com

**Comment by alexchizhovcom** [comment]
@custa1200 Try it again, works perfectly on Android. https://jsfiddle.net/alexchizhov/h5a3coob/

**Comment by custa1200** [comment]
It's still throbbing on iOS :(

**Comment by alexchizhovcom** [comment]
@custa1200 Added font-size to the container and controlls, idk if it helps: https://jsfiddle.net/alexchizhov/h5a3coob/

**Comment by custa1200** [comment]
It did help, throbbing gone.

**Comment by alexchizhovcom** [comment]
great :)

**Comment by alexchizhovcom** [comment]
@custa1200 @technofreaky Version 1.4.0 is out, please, enjoy :)

**Comment by varunsridharan** [comment]
@alexchizhovcom Thank you so much.. i really love your job.. 

I am using this on one of my WordPress Plugin.. will sure give you a proper credit :)
