### ISSUE TITLE
Hooks / Methods

### ISSUE THREAD

**Issue by varunsridharan** [alexchizhovcom/pwstabs#11]
I read the full document and also code to find is there any method / hook to use before the tab is created or after the tab is created.. Like in wordpress Filters / Actions..

I think it would be more useful to add hooks / methods or also jQuery Trigger method which is equivalent to wordpress actions.. :)

**Comment by alexchizhovcom** [comment]
I was thinking on adding events like onclick, onchange, etc. And methods like next, prev and so on. But it needs time to code it, and im really limited with this type of resource right now. But yea, I will definitily add it in the future. If you have any suggestions on what methods and events you might need, that would be helpful.

**Comment by varunsridharan** [comment]
@alexchizhovcom Yes. sure i will send the idea.. and also if possible. i will also code and send you a pull request

**Comment by alexchizhovcom** [comment]
Added new methods and hooks, will be available in the upcoming update.
