### ISSUE TITLE
Height is not setting up correctly

### ISSUE THREAD

**Issue by varunsridharan** [alexchizhovcom/pwstabs#13]
Hi, @alexchizhovcom 

I hope you are doing good..

Today i was testing for my plugin release and found that when using tab position and the tab content height is not getting updated correctly :disappointed: 
Please check the screenshot link : http://prntscr.com/av02g3

its quit bit urgent. i know you are busy.. but i hope i will get an answer

**Comment by alexchizhovcom** [comment]
Hi, @technofreaky 

Providing source code or at least more steps on how to call this issue would be helpful :)

**Comment by alexchizhovcom** [comment]
@technofreaky Does this problem still occur?
