### ISSUE TITLE
Slidedown and slidetop are not working.

### ISSUE THREAD

**Issue by malabya** [alexchizhovcom/pwstabs#14]
The slidetop and slidedown effects are not working. It takes the default scale effect when these effect are chosen.

<pre>`jQuery(document).ready(function($){
  $('.pws-tabs').pwstabs({

  // scale / slideleft / slideright / slidetop / slidedown / none
  effect: 'slidetop',

  // Tabs position: horizontal / vertical
  tabsPosition: 'horizontal',

  // horizontalPosition: 'bottom',
  // verticalPosition: 'left',
  responsive: true,

  // Themes available: default: '' / pws_theme_violet / pws_theme_green / pws_theme_yellow / pws_theme_gold /
  // pws_theme_orange / pws_theme_red / pws_theme_purple / pws_theme_grey
  theme: 'pws_theme_orange',

});
});`</pre>

**Comment by alexchizhovcom** [comment]
@malabya It can be some css or browser support issues. All examples work: http://alexchizhov.com/pwstabs/
What browser do you use? Did you edit css?
