### ISSUE TITLE
register on bower

### ISSUE THREAD

**Issue by goldensunliu** [alexchizhovcom/pwstabs#2]
would be nice if this is bower ready. we just need to creates a bower.json. Let me know if you would like me to do a pull request.

**Comment by alexchizhovcom** [comment]
Thats a good point. Pull request would be great.

**Comment by OogieBoogieInJSON** [comment]
Well, the owner of project should create this. For bower or npm, the .json file contains sensitive data, like real name, keywords, website links. Else, everyone can fork and register as his project, not yours.

**Comment by alexchizhovcom** [comment]
Try this: `bower install pwstabs`

Im not good at working with bower yet, so its my first try.

**Comment by OogieBoogieInJSON** [comment]
Perfect, now it's easier for everyone to implement in it's project.
