### ISSUE TITLE
Integrate styles that works with major frameworks

### ISSUE THREAD

**Issue by shahroq** [alexchizhovcom/pwstabs#3]
Hi,
Just see and tested your plugin. seems cool. i have tested it and i thought it worth mention some behavioral improvement:
1- I tested it with some major css frameworks include bootstrap and zurb foundation. it has some glitches with both. the main point is set ul margin (left,bottom) to 0.
2- At the demo pages body background is a non-white color, it's super cool on dark backgrounds, but at white backgrounds it seems "apart". As long as most of the pages uses white bg, it would be cool if u design a theme for light backgrounds.
Cheers

**Comment by alexchizhovcom** [comment]
Hi and thank you for your support!
Version 2.0.0 is coming in the next two weeks. It has some major improvements in functionality, new functions, controlls, options updates. I already fixed issue with zero margins for ul, and designed new theme for white backgrounds, with borders and shadows of different colors. So it will be there.

**Comment by shahroq** [comment]
Hi,
When do you think the new version would be available?

**Comment by alexchizhovcom** [comment]
2-3 weeks
