### ISSUE TITLE
Usage of multiple tabs structures

### ISSUE THREAD

**Issue by spambas** [alexchizhovcom/pwstabs#4]
Trying to use horizontal tabs with on each tab some vertical tabs.

The horizontal tabs are added to the list of vertical tabs...

H_tab_1 | H_tab_2

```
V_tab_1
V_tab_2
V_tab_3
H_tab_1
H_tab_2
```

**Comment by alexchizhovcom** [comment]
If I get it right, you are talking about nested tabs? If so, it will be corrected in 2.0.0. It is only possible right now, to nest tabs with the same positioning, H & H, or V & V.

**Comment by spambas** [comment]
Ok. Is this an easy fix? Or do I have to wait for version 2.0? 

for your information: everything works. the right tabs are selected when clickin a button, the right transition is running, etc. 
The only error is the adition of the two horizontal tabs in the vertical tabs lists. 

In javascript I also have the vertical tabs first declared, then the horizontal ones...

**Comment by spambas** [comment]
An update:

I moved the declaration off the horizontal tabs so it will be applied before the vertical ones, and this works! (i changed some css)

![image](https://cloud.githubusercontent.com/assets/10828880/6324508/2a6e6ffc-bb3b-11e4-9386-8ac37f6bbc18.png)

![image](https://cloud.githubusercontent.com/assets/10828880/6324534/79e5ea2e-bb3b-11e4-81a5-cdff738ed9b6.png)

![image](https://cloud.githubusercontent.com/assets/10828880/6324494/f9d6ccfe-bb3a-11e4-940a-7ed792e65bf2.png)

**Comment by alexchizhovcom** [comment]
Its not hard to fix, but I gotta work out the new structure for parent block and its children blocks, so it doesn't come to a conflict in different cases of nesting

**Comment by spambas** [comment]
Ok. I will wait on that then, because my shout of joy was a little premature. The auto size function does not seem to work in the vertical tabs now. when I select a vertical tab with a lot of text, the div size does not change. when I then select another horizontal tab, and switch back to the previous one, the size is adjusted and the size of the vertical tab is ok...

So, not really working....

**Comment by murali-kunapareddy** [comment]
Hi alexchizhovcom,

Thank you for great tabs plugin. I am eagerly waiting for NESTED TABS feature in this like spambas in version 2.0. Hope you get time to release this soon.

**Comment by custa1200** [comment]
Any news on this, it's been close to a year since this issue was first raised.. I like what has been done here but I think I need to find another set that are working.

**Comment by custa1200** [comment]
@alexchizhovcom do you have any updates/thoughts on this?

**Comment by alexchizhovcom** [comment]
@spambas @kmuralik Version 1.4.0 is out, please, enjoy :) Nested tabs are added
