### ISSUE TITLE
hide and show

### ISSUE THREAD

**Issue by abelorian** [alexchizhovcom/pwstabs#5]
Hi ¿Is ok this? 

```
<div data-pws-tab="anynameyouwant1" data-pws-tab-name="Tab name 1" class="pws_tabs_scale_hide pws_tab_single pws_tabs_scale_show" data-pws-tab-id="1">
```

'pws_tabs_scale_hide' and 'pws_tabs_scale_show' at the same time in a div?

Version: 1.2.1

**Comment by alexchizhovcom** [comment]
yes, hide class always stays there. the only class changes is `pws_tabs_scale_show`
