### ISSUE TITLE
Dynamicly add tab

### ISSUE THREAD

**Issue by BurakDev** [alexchizhovcom/pwstabs#6]
Hey,

is possible to add dynamicly tab with javascript ?

like 

``` javascript
$('#mytab').append('<div data-pws-tab="tab3" data-pws-tab-name="+" onclick="alert();"></div>');
```

Thanks

**Comment by alexchizhovcom** [comment]
Hi,

It is possible, you need to append a div to a container, and a LI block 
to UL navigation block after plugin initialization.

**Comment by BurakDev** [comment]
Thanks for fast reply, can you make a example ? It will be very useful if you explain it on your demo part

**Comment by alexchizhovcom** [comment]
Im at work so dont have much time now, but you can try this:

// UL - contolls block
var ul = $('ul.pws_tabs_controll');
// Controll block tab
var li = '<li><a data-tab-id="YOURTABID" href="#"></li>';
// Add tab to controll block
ul.append(li);

// Our container with tabs
var container = $('.pws_tabs_list');

// Count how many tabs are in the container
var counter = container.find('.pws_tab_single').length;

// Code for new tab
var newTab = '<div class="pws_tab_single pws_tabs_scale_hide" 
data-pws-tab-name="YOURTABSNAME" data-pws-tab="YOURTABID" 
data-pws-tab-id="'+counter+'">YOUR CONTENT FOR THE TAB</div>';

// Add tab to container
container.append(newTab);

DO NOT FORGET TO:
change pws_tabs_scale_hide class to the class of the effect you are 
using <pws_tabs_EFFECT_hide>

This should work, place this code after you initialize PWSTabs

**Comment by alexchizhovcom** [comment]
Added method addTab, will be available in the upcoming update
